--                            M O O N L I G H T
--      _..._         _..._         _..._         _..._         _..._
--    .:::::::.     .::::. `.     .::::  `.     .::'   `.     .'     `.
--   :::::::::::   :::::::.  :   ::::::    :   :::       :   :         :
--   :::::::::::   ::::::::  :   ::::::    :   :::       :   :         :
--   `:::::::::'   `::::::' .'   `:::::   .'   `::.     .'   `.       .'
--     `':::''       `'::'-'       `'::.-'       `':..-'       `-...-'
--
-- Colorscheme name:    solarized.nvim
-- Description:         Port of VSCode's Moonlight colorscheme for NeoVim
-- Author:              https://github.com/shaunsingh
require('themer.themes.solarized').set()
